# -*- coding: utf-8 -*-
"""Dev_Tool.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b4AagKYeLY1DubzBjToCEsb_Uvrd-z3a
"""

# -*- coding: utf-8 -*-
"""
Created on Thu Nov 25 21:54:50 2021

@author: Priyadarshini Satish
"""
import matplotlib.pyplot as plt
import pandas as pd

filename = 'coverage_table.txt'

data = pd.read_csv(filename,
                   sep="|",
                   engine='python',
                   skiprows=1)
data.columns = data.columns.str.strip()

for c in data.columns[1:] :
    data[c] = data[c].str.lstrip()  # strip leading space from all column data
    data[c] = data[c].str.split(' ', 1, expand=False)  # Split Columns into two

data = data.dropna()

xAxis = []
yAxis = []
for n in range(3, len(data['Lines'])):
    xAxis.append(float(data['Lines'][n][0].replace('%', '')))
    yAxis.append(data[''][n])

plotData = pd.DataFrame(xAxis,yAxis)
plotData.plot(kind='bar')
# plt.tick_params(axis='x', which='major', labelsize=5)
plt.xticks(rotation=90)
plt.show()
